<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RuleWay.ECommerce.Application\RuleWay.ECommerce.Application.csproj" />
    <ProjectReference Include="..\RuleWay.ECommerce.Domain\RuleWay.ECommerce.Domain.csproj" />
  </ItemGroup>

</Project>
